name: Create Joomla installation package

on:
  release:
    types: [ published ]

jobs:

  createReleasePackage:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install git zip unzip -y

      - name: Setup package version in manifests
        run: find -type f -exec sed -i -E 's/(@version\s*\t*|<version>)([0-9a-zA-Z_\.-]+)/\1${{ github.ref_name }}/' {} \;

      - name: Build artifact
        run: |
          export TERM=xterm
          zip -r plg_system_yametrikinsert.zip fields language media script.php yametrikinsert.php yametrikinsert.xml

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: plg_system_yametrikinsert.zip
